name: Build All & Release
on:
  push:
    branches: [ master, test/git-actions ]
    tags:
      - v*


jobs:
  windows-bin:
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modulesTWO-${{ hashFiles('**/yarn.lock') }}

      - name: Install Yarn Packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test Unit
        run: yarn test

      - name: Build Frontend & Electron
        run: yarn build

      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          build_script_name: empty
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
